# Excalibase REST API Configuration
server:
  port: 8080

spring:
  application:
    name: excalibase-rest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # Connection pool configuration
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    idle-timeout: 300000
    connection-timeout: 20000
    max-lifetime: 1200000

  # Jackson configuration for JSON processing
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Application-specific configuration
app:
  # Database configuration
  allowed-schema: public
  database-type: postgres
  
  # Pagination configuration
  max-page-size: 1000
  default-page-size: 100
  
  # Cache configuration
  schema-cache-ttl-seconds: 300 # 5 minutes
  
  # CORS configuration
  cors:
    enabled: true
    allowed-origins: 
      - "*"
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: false
    max-age: 3600
  
  # Security configuration
  security:
    enable-sql-injection-protection: true
    enable-table-name-validation: true
    enable-column-name-validation: true
    max-request-body-size: 1048576 # 1MB
    max-query-complexity: 100
  
  # Query complexity limits
  query:
    max-complexity-score: 1000
    max-depth: 10
    max-breadth: 50
    complexity-analysis-enabled: true

# Logging configuration
logging:
  level:
    io.github.excalibase: INFO
    org.springframework.jdbc.core: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints (actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

# Application information
info:
  app:
    name: Excalibase REST API
    description: Auto-generated REST API for PostgreSQL databases
    version: 1.0.0
    github: https://github.com/excalibase/excalibase-rest